# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀
$mainMod = SUPER 
bind = $mainMod, c, killactive
bindd = $mainMod, b, browser, exec, librewolf
bindd = $mainMod, q, kitty, exec, kitty
bindd = $mainMod, n, yazi, exec, yazi
bind = $mainMod, E, exec, dolphin
bind = $mainMod shift, r, exec, hyprctl reload;
bind = $mainMod, space, exec, rofi -combi-modi window,drun,ssh,run -show combi -show-icons
bind = $mainMod, n, exec, "command -v btop && kitty

# vim movement focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# move window with vim keys
bind = $mainMod shift, h, movewindow, l
bind = $mainMod shift, l, movewindow, r
bind = $mainMod shift, k, movewindow, u
bind = $mainMod shift, j, movewindow, d

# workspace switch
bind = $mainMod, f, workspace, +1
bind = $mainMod, d, workspace, -1
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░
bind = $mainMod, C, killactive, # close the active window
bind = $mainMod SHIFT, Q, exit,
bind = $mainMod, V, togglefloating, # Allow a window to float
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, M, togglesplit, # dwindle
bind = $mainMod, G, fullscreen,

# Media keys - Play/Pause
bind = , XF86AudioPlay, exec, playerctl play-pause && ~/.config/hypr/scripts/player-notify.sh
bind = , XF86AudioPause, exec, playerctl play-pause && ~/.config/hypr/scripts/player-notify.sh

# Media keys - Next/Previous
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Volume control
bind = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/volume-notify.sh up
bind = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volume-notify.sh down
bind = , XF86AudioMute, exec, ~/.config/hypr/scripts/volume-notify.sh mute

# Brightness control
bind = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness-notify.sh up
bind = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness-notify.sh down

##! Session
bindd = Super, return, Lock, exec, hyprlock # Lock
