
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄
# see https://wiki.hyprland.org/configuring/monitors/
monitor=,preferred,auto,1
monitor=eDP-1,2256x1504@60,0x0,1.177
monitor=DP-9,3440x1440@85,-3440x0,1
monitor=DP-10,3440x1440@85,-3440x0,1
# Lid switch - disable eDP-1 when lid closes
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, enable"
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
